FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .
COPY requirements.streamlit.txt .
RUN pip install --no-cache-dir -r requirements.streamlit.txt
COPY corrective_rag.py .

CMD ["streamlit", "run", "corrective_rag.py", "--server.address=0.0.0.0", "--server.port=8501"]
